const cats = [
  "Acil Tıp",
  "Allerji ve İmmünoloji Hastalıkları",
  "Androloji",
  "Anestezi ve Reanimasyon",
  "Ağız ve Diş Sağlığı",
  "Beslenme ve Diyet",
  "Beyin ve Sinir",
  "Biyokimya",
  "Cildiye",
  "Dahiliye",
  "Deri ve Zührevi Hastalıklar",
  "Dermatoloji",
  "Diyetisyen",
  "Diş Hekimi",
  "Enfeksiyon",
  "Erişkin Psikiyatrisi",
  "Estetik",
  "Fizik Tedavi ve Rehabilitasyon",
  "Gastroenteroloji",
  "Genel Cerrahi",
  "Genetik",
  "Geriatri ",
  "Göğüs Hastalıkarı",
  "Göğüs Cerrahisi",
  "Göz Hastalıkları",
  "Hematoloji",
  "Hepatoloji Bilim Uzmanı",
  "Kadın Hastalıkları ve Doğum",
  "Kalp ve Damar Cerrahisi",
  "Kardiyoloji",
  "Kulak Burun Boğaz",
  "Moleküler Mikrobiyoloji",
  "Nefroloji ve İç Hastalıkları",
  "Nöroloji",
  "Nükleer Tıp",
  "Onkoloji",
  "Ortopedi ve Travmatoloji",
  "Patoloji",
  "Pediatrik Kardiyoloji",
  "Perinatolog",
  "Plastik Cerrahi ve Rejeneratif Tıp",
  "Pratisyen Hekim",
  "Psikiyatri",
  "Psikolog",
  "Psikolog",
  "Radyoloji",
  "Romatoloji",
  "Tüp Bebek ve Üreme",
  "Tıbbi Biyokimya",
  "Yenidoğan Yoğun Bakım",
  "Yoğun Bakım Sorumlu Hekimi",
  "Çocuk Endokrinolojisi ve Metabolizma Hastalıkları",
  "Çocuk Gastroenterolojisi",
  "Çocuk Hastalıkları",
  "Çocuk Kardiyolojisi",
  "Çocuk Nefrolojisi ve Romatolojisi",
  "Çocuk Nörolojisi",
  "Çocuk Psikiyatrisi",
  "Çocuk Sağlığı ve Hastalıkları",
  "Çocuk İmmünoloji ve Alerjisi",
  "Üroloji",
  "İmmunoloji ve Alerji Hastalıkları",
  "İç Hastalıklar",
];

const hash = {
  A: [
    "Acil Tıp",
    "Allerji ve İmmünoloji Hastalıkları",
    "Androloji",
    "Anestezi ve Reanimasyon",
    "Ağız ve Diş Sağlığı",
  ],
  B: ["Beslenme ve Diyet", "Beyin ve Sinir", "Biyokimya"],
  C: ["Cildiye"],
  D: [
    "Dahiliye",
    "Deri ve Zührevi Hastalıklar",
    "Dermatoloji",
    "Diyetisyen",
    "Diş Hekimi",
  ],
  E: ["Enfeksiyon", "Erişkin Psikiyatrisi", "Estetik"],
  F: ["Fizik Tedavi ve Rehabilitasyon"],
  G: [
    "Gastroenteroloji",
    "Genel Cerrahi",
    "Genetik",
    "Geriatri ",
    "Göğüs Hastalıkarı",
    "Göğüs Cerrahisi",
    "Göz Hastalıkları",
  ],
  H: ["Hematoloji", "Hepatoloji Bilim Uzmanı"],
  K: [
    "Kadın Hastalıkları ve Doğum",
    "Kalp ve Damar Cerrahisi",
    "Kardiyoloji",
    "Kulak Burun Boğaz",
  ],
  M: ["Moleküler Mikrobiyoloji"],
  N: ["Nefroloji ve İç Hastalıkları", "Nöroloji", "Nükleer Tıp"],
  O: ["Onkoloji", "Ortopedi ve Travmatoloji"],
  P: [
    "Patoloji",
    "Pediatrik Kardiyoloji",
    "Perinatolog",
    "Plastik Cerrahi ve Rejeneratif Tıp",
    "Pratisyen Hekim",
    "Psikiyatri",
    "Psikolog",
    "Psikolog",
  ],
  R: ["Radyoloji", "Romatoloji"],
  T: ["Tüp Bebek ve Üreme", "Tıbbi Biyokimya"],
  Y: ["Yenidoğan Yoğun Bakım", "Yoğun Bakım Sorumlu Hekimi"],
  Ç: [
    "Çocuk Endokrinolojisi ve Metabolizma Hastalıkları",
    "Çocuk Gastroenterolojisi",
    "Çocuk Hastalıkları",
    "Çocuk Kardiyolojisi",
    "Çocuk Nefrolojisi ve Romatolojisi",
    "Çocuk Nörolojisi",
    "Çocuk Psikiyatrisi",
    "Çocuk Sağlığı ve Hastalıkları",
    "Çocuk İmmünoloji ve Alerjisi",
  ],
  Ü: ["Üroloji"],
  İ: ["İmmunoloji ve Alerji Hastalıkları", "İç Hastalıklar"],
};

export default hash;
